In [8]:
#importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer

#importing the datasets
dataset = pd.read_csv('E:/user/Documents/ulster/ml/data/Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

# taking care of missing values
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x [:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

 # print(x[:, 1:3])

# Encoding categorical data
# Encoding the Independent Variable
ct  =  ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

print(x)

# Encoding the Dependent Variable
le = LabelEncoder()
y = le.fit_transform(y)

print(y)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
[0 1 0 0 1 1 0 1 0 1]


In [11]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
# x_train ===  the matrix features of the training set
# x_test === the matrix features of the test set
# y_train === the dependent variable of the training set
# y_test === the dependent variable of the test set
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1 )

In [12]:
print(x_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [13]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [14]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [15]:
print(y_test)

[0 1]
